# fly.toml app configuration file generated for charson-secret-santa on 2023-11-06T17:55:53+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "charson-secret-santa"
primary_region = "cdg"

[build]

[env]
  DATABASE_URL = "file:/data/sqlite.db"
  PORT = "3000"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
